# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: buildConfig
    type: string
    default: 'development'
    values:
      - production
      - development
      - fake

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    echo "Angular Config: ${{ parameters.buildConfig }}"
    npm install -g @angular/cli
    npm install
    ng build --configuration=${{ parameters.buildConfig }}
  displayName: 'npm install and build'
